name: CMake

on:
  push:
    branches: 
    - 'main'
  pull_request:
    branches: 
    - 'main'

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-latest
        - os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
  
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1
      with:
        version: '1.11.1'

    # https://github.com/zhuzichu520/FluentUI/blob/06c9b4e3829af636234a98f946603d68c23f6459/.github/workflows/ubuntu.yml#L49-L50
    - name: Install GL library (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt-get install -y libxcb-cursor0 libgl1-mesa-dev libxcb1-dev libgtk-3-dev libxkbcommon-x11-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-sync-dev  libxcb-render-util0-dev libxcb-shm0-dev 

    - name: Setup MSVC Environment
      uses: TheMrMilchmann/setup-msvc-dev@v2
      if: runner.os == 'Windows'
      with:
        arch: x64
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        modules: 'qt5compat qtwebsockets qthttpserver'
        cache: 'true'
        cache-key-prefix: 'install-qt-action'

    - name: Configure CMake
      run: cmake -G Ninja -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_PREFIX_PATH=${{env.Qt6_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Bin-${{env.BUILD_TYPE}}-${{runner.os}}
        path: ${{github.workspace}}/bin
